- name: Set up application infrastructure on Minikube
  hosts: localhost
  tasks:
    - name: Get MySQL master status
      community.mysql.mysql_query:
        login_host: "{{ hostvars['auth-master-sfs-0'].ansible_host }}"
        login_user: "{{ hostvars['auth-master-sfs-0'].mysql_user }}"
        login_password: "{{ hostvars['auth-master-sfs-0'].mysql_password }}"
        db: "{{ hostvars['auth-master-sfs-0'].db_name }}"
        query: 'SHOW MASTER STATUS;'
      register: master_status

    - name: Configure MySQL slave
      community.mysql.mysql_query:
        login_host: "{{ hostvars['auth-slave-sfs-0'].ansible_host }}"
        login_user: "{{ hostvars['auth-slave-sfs-0'].mysql_user }}"
        login_password: "{{ hostvars['auth-slave-sfs-0'].mysql_password }}"
        db: "{{ hostvars['auth-slave-sfs-0'].db_name }}"
        query: >
          CHANGE MASTER TO MASTER_LOG_FILE='{{ master_status.result[0].File }}',
          MASTER_LOG_POS={{ master_status.result[0].Position }};
        start_slave: yes

    - name: Populate MySQL master with initial data
      community.mysql.mysql_query:
        login_host: "{{ hostvars['auth-master-sfs-0'].ansible_host }}"
        login_user: "{{ hostvars['auth-master-sfs-0'].mysql_user }}"
        login_password: "{{ hostvars['auth-master-sfs-0'].mysql_password }}"
        db: "{{ hostvars['auth-master-sfs-0'].db_name }}"
        query: "{{ lookup('file', '/etc/setup.sql') }}"
      #shell: minikube kubectl -- exec -it auth-master-sfs-0 -- mysql -u auth_user -padminpass -e < /etc/setup.sql
