apiVersion: v1
kind: Service
metadata:
  name: auth-slave-service
  labels:
    app: auth-slave-service
spec:
  ports:
  - port: 3306
    targetPort: 3306
    protocol: TCP
  type: ClusterIP
  selector:
    app: auth-slave