apiVersion: v1
kind: Service
metadata:
  name: auth-master-headless-service
  labels:
    app: auth-master-headless-service
spec:
  ports:
  - port: 3306
    targetPort: 3306
    protocol: TCP
  type: ClusterIP
  clusterIP: None
  selector:
    app: auth-master