apiVersion: v1
kind: ConfigMap
metadata:
  name: auth-mysql-config
data:
  my.cnf: |
    [mysqld]
    user = mysql
    port = 3306
    datadir = /var/lib/mysql
    server-id = 1
    log_bin = /var/log/mysql/mysql-bin.log
    binlog_format = ROW
    sync_binlog = 1
    relay-log = /var/log/mysql/mysql-relay-bin.log
    bind-address = 0.0.0.0
    max_connections = 200

  init.sql: |
    START TRANSACTION;

    CREATE DATABASE IF NOT EXISTS authdb;
    USE authdb;

    CREATE USER IF NOT EXISTS 'auth_user'@'%' IDENTIFIED BY 'Aauth123';
    GRANT ALL PRIVILEGES ON authdb.* TO 'auth_user'@'%';

    CREATE USER IF NOT EXISTS 'replica_user'@'%' IDENTIFIED BY 'replica_password';
    GRANT REPLICATION SLAVE ON *.* TO 'replica_user'@'%';

    FLUSH PRIVILEGES;

    CREATE TABLE IF NOT EXISTS user (
        id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
        email VARCHAR(255) NOT NULL UNIQUE,
        password VARCHAR(255) NOT NULL
    );

    INSERT INTO user (email, password)
    VALUES ('test@gmail.com', 'Admin123')
    ON DUPLICATE KEY UPDATE email=email;

    COMMIT;